=== felixdorn/Release-that/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Release that config",
  "type": "object",
  "properties": {
    "origin": {
      "type": "string"
    },
    
    "release_notes": {
      "type": "object",
      "properties": {
        "commit_format": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "ignore": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "before_release": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "after_release": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "assets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tag_message": {
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== felixdorn/Release-that/rt.json
{
  "$schema": "https://raw.githubusercontent.com/felixdorn/release-that/main/schema.json",
  "release_notes": {
    "commit_format": "* :hash: :message",
    "title": "Release :version"
  },
  "before_release": [
    "go build -ldflags='-w -s -X github.com/me/rt/globals.Version=:version' -gcflags=all='-l'"
  ],
  "after_release": [],
  "assets": [
    "./rt"
  ],
  "tag_message": "Version :tag"
  
}
